image: "python:3.7"

before_script:
  - python --version
  - pip install flake8
  - flake8 --version
  - pip install pylint
  - pylint --version
  - pip install radon
  - radon --version
  - shopt -s globstar

stages:
  - Metrics
  - Code grade_allowed to fail
  - Static Analysis
  - Complexity Analysis
  
Complexity:
  stage: Metrics
  script:
  - radon cc **/*.py -a
  
Maintainability:
  stage: Metrics
  script:
  - radon mi **/*.py
  
Raw metrics:
  stage: Metrics
  script:
  - radon raw **/*.py
  


Code grade:
  stage: Code grade_allowed to fail
  script:
  - pylint detecht_backend/detecht_backend/*.py
  allow_failure: true

StaticFlake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=79 --benchmark
  allow_failure: true
  
ComplexityFlakeTest:
  stage: Complexity Analysis
  script:
  - flake8 --max-complexity 10 --benchmark
  allow_failure: true
