image: "python:3.7"
include:
  template: Dependency-Scanning.gitlab-ci.yml

before_script:
  - python --version
  - pip install flake8
stages:
  - Static Analysis
  - dependency_scanning

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 detecht_backend/detecht_backend/*.py
  

scan:
  stage: scan
  script:
  dependency_scanning:
  variables:
    CI_DEBUG_TRACE: "true"