image: "python:3.7"

before_script:
  - python --version
  - pip install flake8
stages:

  - Static Analysis
  - Complexity Analysis
  
StaticFlake8:
  stage: Static Analysis
  script:
  - flake8 --benchmark
  
ComplexityFlakeTest:
  stage: Complexity Analysis
  script:
  - flake8 --max-complexity 10 --benchmark
