image: python:latest
stages:
    - build
    - test
    
build:
    stage: build
    script:
        - echo "Building"
       
        
test:
    stage: test
    script:
        - echo "Testing"
        