image: "python:3.7"

before_script:
  - python --version
  - pip install flake8
stages:

  - Static Analysis

  
ComplexityFlakeTest:
  stage: Static Analysis
  script:
  - flake8 --max-complexity 10 --benchmark
