# Generated by Django 2.2.5 on 2019-09-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTry',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
