# Generated by Django 2.2.5 on 2019-11-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFImportance',
        ),
        migrations.AddField(
            model_name='document',
            name='custom_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='favorites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
