# Generated by Django 2.2.5 on 2019-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Autocomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_gram', models.TextField()),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
