# Generated by Django 2.2.5 on 2019-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0002_auto_20190930_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
