# Generated by Django 2.2.5 on 2019-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0006_auto_20191015_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Name_Keyword_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.TextField(max_length=50)),
                ('keyword', models.TextField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
