# Generated by Django 2.2.5 on 2019-11-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0007_stagedpdf_stagedpdftags'),
        ('detecht_api', '0007_pdf_name_keyword_weight'),
    ]

    operations = [
    ]
