# Generated by Django 2.2.5 on 2019-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0008_merge_20191106_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
