# Generated by Django 2.2.5 on 2019-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0008_merge_20191106_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Similarities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name1', models.TextField(max_length=50)),
                ('document_name2', models.TextField(max_length=50)),
                ('similarity', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
