# Generated by Django 2.2.5 on 2019-11-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0009_auto_20191108_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImportance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('custom_weight', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='keyword_distance',
            name='id_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='keyword_distance',
            name='id_2',
            field=models.PositiveIntegerField(),
        ),
    ]
