# Generated by Django 2.2.5 on 2019-11-06 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0009_searches_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches_database',
            name='search_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
