# Generated by Django 2.2.5 on 2019-11-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0008_merge_20191106_1742'),
        ('detecht_api', '0009_auto_20191108_0958'),
    ]

    operations = [
    ]
