# Generated by Django 2.2.5 on 2019-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0010_auto_20191111_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField(max_length=20)),
                ('keyword', models.TextField(max_length=50)),
            ],
        ),
    ]
