# Generated by Django 2.2.5 on 2019-11-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0010_auto_20191106_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searches_Database',
        ),
    ]
