# Generated by Django 2.2.5 on 2019-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0010_auto_20191111_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacted_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_prev', models.TextField(max_length=30)),
                ('date', models.DateField()),
                ('pdf_name', models.TextField(max_length=50)),
                ('userid', models.TextField(max_length=20)),
            ],
        ),
    ]
