# Generated by Django 2.2.5 on 2019-11-12 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0010_merge_20191112_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacted_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_prev', models.TextField(max_length=30)),
                ('date', models.DateField()),
                ('pdf_name', models.TextField(max_length=50)),
                ('userid', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PDFImportance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('custom_weight', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Searches_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(max_length=50)),
                ('standardized_search_query', models.CharField(max_length=50)),
                ('search_score', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='User_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField(max_length=20)),
                ('keyword', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword_distance',
            name='id_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='keyword_distance',
            name='id_2',
            field=models.PositiveIntegerField(),
        ),
    ]
