# Generated by Django 2.2.5 on 2019-11-11 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0011_delete_searches_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(max_length=50)),
                ('standardized_search_query', models.CharField(max_length=50)),
                ('search_score', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
