# Generated by Django 2.2.5 on 2019-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0011_auto_20191112_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
    ]
