# Generated by Django 2.2.5 on 2019-11-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0012_searches_database'),
        ('detecht_api', '0010_auto_20191111_2258'),
    ]

    operations = [
    ]
