# Generated by Django 2.2.5 on 2019-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecht_api', '0014_auto_20191127_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=50)),
                ('frequency', models.BigIntegerField(default=1)),
            ],
        ),
    ]
